version: '3.8'
name: predictions
services:
  app:
    container_name: pred-app
    image: pred-app
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      test: [ 'CMD', 'curl --fail http://localhost:8000/ || exit 1' ]
      interval: 3s
      timeout: 5s
      retries: 3
    networks:
      - pred-network

networks:
  pred-network:
