version: '3.8'
name: predictions
services:
  app:
    container_name: pred-app
    image: pred-app
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: on-failure
    healthcheck:
      interval: 3s
      timeout: 5s
      retries: 3
    networks:
      - pred-network
  db:
    image: postgres:16.2
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${DB_PASSWORD?Variable not set}
      - POSTGRES_USER=${DB_USER?Variable not set}
      - POSTGRES_DB=${DB_DBNAME?Variable not set}

networks:
  pred-network:

volumes:
  app-db-data:
